<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="csrf-token" content="{{ csrf_token() }}" />

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=figtree:400,500,600&display=swap" rel="stylesheet" />

    @php
        // path to Vite manifest generated by `npm run build`
        $viteManifest = public_path('build/manifest.json');
    @endphp

    @if (file_exists($viteManifest))
        {{-- If manifest exists use Vite (recommended for production/dev with vite running) --}}
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    @else
        {{-- Fallback assets when manifest is not present (prebuilt theme assets) --}}
        <link rel="stylesheet" href="{{ asset('assets/css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ asset('assets/css/fontawesome.min.css') }}">
        <link rel="stylesheet" href="{{ asset('assets/css/magnific-popup.min.css') }}">
        <link rel="stylesheet" href="{{ asset('assets/css/swiper-bundle.min.css') }}">
        <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
        {{-- Optionally include any other vendor CSS your theme needs here --}}
    @endif

    @livewireStyles
</head>
<body class="antialiased">
    <div class="font-sans text-gray-900">
        {{ $slot }}
    </div>

    {{-- Always include Livewire scripts --}}
    @livewireScripts

    @if (file_exists($viteManifest))
        {{-- Vite will inject necessary scripts --}}
    @else
        {{-- Fallback JS for guests when Vite is not available --}}
        <script src="{{ asset('assets/js/vendor/jquery-3.6.0.min.js') }}" defer></script>
        <script src="{{ asset('assets/js/swiper-bundle.min.js') }}" defer></script>
        <script src="{{ asset('assets/js/bootstrap.min.js') }}" defer></script>
        <script src="{{ asset('assets/js/jquery.magnific-popup.min.js') }}" defer></script>
        <script src="{{ asset('assets/js/jquery.counterup.min.js') }}" defer></script>
        <script src="{{ asset('assets/js/jquery-ui.min.js') }}" defer></script>
        <script src="{{ asset('assets/js/imagesloaded.pkgd.min.js') }}" defer></script>
        <script src="{{ asset('assets/js/isotope.pkgd.min.js') }}" defer></script>
        <script src="{{ asset('assets/js/gsap.min.js') }}" defer></script>
        <script src="{{ asset('assets/js/circle-progress.js') }}" defer></script>
        <script src="{{ asset('assets/js/matter.min.js') }}" defer></script>
        <script src="{{ asset('assets/js/matterjs-custom.js') }}" defer></script>
        <script src="{{ asset('assets/js/nice-select.min.js') }}" defer></script>
        <script src="{{ asset('assets/js/main.js') }}" defer></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11" defer></script>
    @endif
</body>
</html>
